# Generated by Django 6.0.6 on 2026-06-09 13:44

import django.db.models.deletion
import encrypted_fields.fields
import jasonstudio.accounts.models
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPayment",
            fields=[
                ("date_created", models.DateTimeField(blank=True, editable=False)),
                ("date_modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "user_created",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who created this record.",
                        max_length=150,
                    ),
                ),
                (
                    "user_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who last modified this record.",
                        max_length=150,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("date", models.DateField(help_text="Date the payment was received.")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("etransfer", "E-Transfer"),
                            ("credit_card", "Credit Card"),
                            ("cheque", "Cheque"),
                            ("other", "Other"),
                        ],
                        default="etransfer",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        help_text="Transaction ID, cheque number, etc.",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical payment",
                "verbose_name_plural": "historical payments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalQuotation",
            fields=[
                ("date_created", models.DateTimeField(blank=True, editable=False)),
                ("date_modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "user_created",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who created this record.",
                        max_length=150,
                    ),
                ),
                (
                    "user_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who last modified this record.",
                        max_length=150,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "quote_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Auto-generated quote number.",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(help_text="Date of the quotation.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Quote expires after this date.",
                        null=True,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Deposit required before the shoot.",
                        max_digits=10,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Who accepted: 'customer' or 'photographer'.",
                        max_length=50,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical quotation",
                "verbose_name_plural": "historical quotations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "user_created",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who created this record.",
                        max_length=150,
                    ),
                ),
                (
                    "user_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who last modified this record.",
                        max_length=150,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated invoice number.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("date", models.DateField(help_text="Date of the invoice.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Deposit amount credited from the order.",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax percentage at time of invoice.",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(max_length=300)),
                ("filename", models.CharField(blank=True, default="", max_length=300)),
                (
                    "qty",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "user_created",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who created this record.",
                        max_length=150,
                    ),
                ),
                (
                    "user_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who last modified this record.",
                        max_length=150,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        blank=True,
                        help_text="Short reference code for this order.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("date", models.DateField(help_text="Date of the order.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("paid", "Paid"),
                            ("in_progress", "In Progress"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When payment was received. Download link expires 30 days after this.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "user_created",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who created this record.",
                        max_length=150,
                    ),
                ),
                (
                    "user_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who last modified this record.",
                        max_length=150,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(help_text="Date the payment was received.")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("etransfer", "E-Transfer"),
                            ("credit_card", "Credit Card"),
                            ("cheque", "Cheque"),
                            ("other", "Other"),
                        ],
                        default="etransfer",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        help_text="Transaction ID, cheque number, etc.",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PhotographerProfile",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "user_created",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who created this record.",
                        max_length=150,
                    ),
                ),
                (
                    "user_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who last modified this record.",
                        max_length=150,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "phone",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, default="", max_length=20, null=True
                    ),
                ),
                (
                    "email",
                    encrypted_fields.fields.EncryptedEmailField(
                        blank=True, default="", max_length=254, null=True
                    ),
                ),
                (
                    "address",
                    encrypted_fields.fields.EncryptedTextField(
                        blank=True, default="", help_text="Business address.", null=True
                    ),
                ),
                (
                    "payment_instructions",
                    encrypted_fields.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="Payment details shown on invoices (bank, Venmo, etc.).",
                        null=True,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        default="Due within 30 days",
                        help_text="e.g. 'Due within 30 days', 'Due on receipt'.",
                        max_length=100,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax percentage (e.g. 13.00 for 13%).",
                        max_digits=5,
                    ),
                ),
                (
                    "invoice_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Default terms/notes shown at the bottom of invoices.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "user_created",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who created this record.",
                        max_length=150,
                    ),
                ),
                (
                    "user_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who last modified this record.",
                        max_length=150,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated quote number.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("date", models.DateField(help_text="Date of the quotation.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Quote expires after this date.",
                        null=True,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Deposit required before the shoot.",
                        max_digits=10,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Who accepted: 'customer' or 'photographer'.",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="QuotationLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(max_length=300)),
                (
                    "qty",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "user_created",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who created this record.",
                        max_length=150,
                    ),
                ),
                (
                    "user_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who last modified this record.",
                        max_length=150,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "phone",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, default="", max_length=20, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="DownloadToken",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "user_created",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who created this record.",
                        max_length=150,
                    ),
                ),
                (
                    "user_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who last modified this record.",
                        max_length=150,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=jasonstudio.accounts.models._generate_download_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Token expires after this datetime."
                    ),
                ),
                (
                    "sent_to_email",
                    encrypted_fields.fields.EncryptedEmailField(
                        blank=True,
                        default="",
                        help_text="Email address the link was sent to.",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_tokens",
                        to="accounts.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalInvoice",
            fields=[
                ("date_created", models.DateTimeField(blank=True, editable=False)),
                ("date_modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "user_created",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who created this record.",
                        max_length=150,
                    ),
                ),
                (
                    "user_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who last modified this record.",
                        max_length=150,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Auto-generated invoice number.",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(help_text="Date of the invoice.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Deposit amount credited from the order.",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax percentage at time of invoice.",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical invoice",
                "verbose_name_plural": "historical invoices",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOrder",
            fields=[
                ("date_created", models.DateTimeField(blank=True, editable=False)),
                ("date_modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "user_created",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who created this record.",
                        max_length=150,
                    ),
                ),
                (
                    "user_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who last modified this record.",
                        max_length=150,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Short reference code for this order.",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(help_text="Date of the order.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("paid", "Paid"),
                            ("in_progress", "In Progress"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When payment was received. Download link expires 30 days after this.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical order",
                "verbose_name_plural": "historical orders",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
