# Generated by Django 6.0.6 on 2026-06-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photographerprofile",
            name="email_body_template",
            field=models.TextField(
                blank=True,
                default='Hi {customer_name},\n\nYour photos from "{event_name}" are ready for download.\n\nClick the link below to download your photos:\n\n{download_url}\n\nThank you for choosing {photographer_name}.',
                help_text="Body for download emails. Placeholders: {customer_name}, {event_name}, {photographer_name}, {download_url}",
            ),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="email_subject_template",
            field=models.CharField(
                blank=True,
                default='Your photos from "{event_name}" are ready',
                help_text="Subject line for download emails. Placeholders: {customer_name}, {event_name}, {photographer_name}",
                max_length=200,
            ),
        ),
    ]
