# Generated by Django 6.0.6 on 2026-06-10 00:12

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_photographerprofile_email_body_template_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "user_created",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who created this record.",
                        max_length=150,
                    ),
                ),
                (
                    "user_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who last modified this record.",
                        max_length=150,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "delivery_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated delivery number.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("google_drive", "Google Drive"),
                            ("email", "Email Link"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Download link (Google Drive URL, token link, etc.).",
                        max_length=500,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="accounts.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "deliveries",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalDelivery",
            fields=[
                ("date_created", models.DateTimeField(blank=True, editable=False)),
                ("date_modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "user_created",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who created this record.",
                        max_length=150,
                    ),
                ),
                (
                    "user_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Username of the user who last modified this record.",
                        max_length=150,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "delivery_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Auto-generated delivery number.",
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("google_drive", "Google Drive"),
                            ("email", "Email Link"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Download link (Google Drive URL, token link, etc.).",
                        max_length=500,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical delivery",
                "verbose_name_plural": "historical deliveries",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
