# Generated by Django 6.0.6 on 2026-06-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_photographerprofile_email_body_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="drive_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Google Drive download link for customer delivery.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="drive_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Google Drive download link for customer delivery.",
                max_length=500,
            ),
        ),
    ]
