# Generated by Django 6.0.6 on 2026-06-10 00:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_delivery_historicaldelivery"),
        ("gallery", "0002_default_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("partially_delivered", "Partially Delivered"),
                    ("delivered", "Delivered"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("partially_delivered", "Partially Delivered"),
                    ("delivered", "Delivered"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DeliveryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="accounts.delivery",
                    ),
                ),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_items",
                        to="gallery.selection",
                    ),
                ),
            ],
            options={
                "ordering": ["delivery"],
            },
        ),
    ]
