# Generated by Django 6.0.6 on 2026-06-08 20:01

import django.db.models.deletion
import gallery.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "default_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("per_hour", "Per Hour"),
                            ("per_image", "Per Image"),
                            ("per_km", "Per Km"),
                            ("flat", "Flat Fee"),
                            ("each", "Each"),
                        ],
                        default="per_hour",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("location", models.CharField(blank=True, default="", max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "customers",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="accounts.customer"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original",
                    models.ImageField(
                        max_length=300, upload_to=gallery.models.photo_upload_path
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        default="",
                        help_text="Resized watermarked version for gallery browsing.",
                        max_length=300,
                        upload_to=gallery.models.thumbnail_upload_path,
                    ),
                ),
                (
                    "watermarked",
                    models.ImageField(
                        blank=True,
                        default="",
                        help_text="Full-resolution watermarked version.",
                        max_length=300,
                        upload_to=gallery.models.watermarked_upload_path,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Custom legend by photographer.",
                    ),
                ),
                ("filename", models.CharField(blank=True, default="", max_length=300)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="Original file size in bytes."
                    ),
                ),
                ("image_width", models.PositiveIntegerField(default=0)),
                ("image_height", models.PositiveIntegerField(default=0)),
                (
                    "camera_model",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("date_taken", models.DateTimeField(blank=True, null=True)),
                (
                    "focal_length",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("aperture", models.CharField(blank=True, default="", max_length=50)),
                (
                    "shutter_speed",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("iso", models.CharField(blank=True, default="", max_length=50)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="gallery.event",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=8, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_link",
                        to="accounts.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Selection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            ("digital", "Digital"),
                            ("both", "Print & Digital"),
                            ("reject", "Reject"),
                        ],
                        default="digital",
                        max_length=20,
                    ),
                ),
                (
                    "print_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("4x6", "4×6"),
                            ("5x7", "5×7"),
                            ("8x10", "8×10"),
                            ("4x4", "4×4"),
                            ("8x8", "8×8"),
                            ("4x5.3", "4×5.3"),
                        ],
                        default="4x6",
                        help_text="Print size, only applicable when choice is Print & Digital.",
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="accounts.customer",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="gallery.photo",
                    ),
                ),
            ],
            options={
                "unique_together": {("photo", "customer")},
            },
        ),
    ]
